# Generated by Django 4.1.6 on 2023-02-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="Email",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="Message",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="Name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="Subject",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="Branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BA", "BA"),
                    ("BBA", "BBA"),
                    ("BLIS", "BLIS"),
                    ("MA", "MA"),
                    ("MEDICAL", "MEDICAL"),
                    ("MBA", "MBA"),
                    ("BOSSE", "BOSSE"),
                    ("BCOM", "BCOM"),
                    ("BSC", "BSC"),
                    ("BSW", "BSW"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="Email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="Name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="Phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="Place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
