# Generated by Django 4.1.4 on 2023-02-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_alter_contact_email_alter_contact_message_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="register",
            new_name="apply",
        ),
    ]
